import prisma from './database.js';

export async function getAllSpecies() {
  return prisma.plantSpecies.findMany({
    orderBy: { commonNameRu: 'asc' },
  });
}

export async function getSpeciesById(id: string) {
  return prisma.plantSpecies.findUnique({
    where: { id },
  });
}

export async function searchSpecies(query: string) {
  return prisma.plantSpecies.findMany({
    where: {
      OR: [
        { commonNameRu: { contains: query, mode: 'insensitive' } },
        { commonNameEn: { contains: query, mode: 'insensitive' } },
        { scientificName: { contains: query, mode: 'insensitive' } },
      ],
    },
    orderBy: { commonNameRu: 'asc' },
    take: 20,
  });
}

// Seed initial plant species data
export async function seedSpecies() {
  const species = [
    {
      scientificName: 'Ficus benjamina',
      commonNameRu: 'Фикус Бенджамина',
      commonNameEn: 'Weeping Fig',
      description: 'Популярное комнатное растение с глянцевыми листьями',
      wateringFrequencyDays: 7,
      wateringWinterMultiplier: 0.5,
      wateringSummerMultiplier: 1.3,
      lightLevel: 'MEDIUM',
      humidityLevel: 'MEDIUM',
      temperatureMin: 16,
      temperatureMax: 24,
      lightingTips: 'Яркий рассеянный свет. Избегайте прямых солнечных лучей.',
      wateringTips: 'Поливайте, когда верхний слой почвы подсохнет на 2-3 см.',
      humidityTips: 'Опрыскивайте листья 2-3 раза в неделю.',
      feedingTips: 'Подкармливайте с весны до осени каждые 2 недели.',
      repottingTips: 'Пересаживайте молодые растения ежегодно, взрослые — раз в 2-3 года.',
    },
    {
      scientificName: 'Monstera deliciosa',
      commonNameRu: 'Монстера',
      commonNameEn: 'Swiss Cheese Plant',
      description: 'Тропическое растение с характерными резными листьями',
      wateringFrequencyDays: 7,
      wateringWinterMultiplier: 0.6,
      wateringSummerMultiplier: 1.2,
      lightLevel: 'MEDIUM',
      humidityLevel: 'HIGH',
      temperatureMin: 18,
      temperatureMax: 27,
      lightingTips: 'Яркий рассеянный свет. Выносит полутень.',
      wateringTips: 'Поливайте обильно, давая почве немного подсохнуть между поливами.',
      humidityTips: 'Любит высокую влажность. Регулярно опрыскивайте.',
      feedingTips: 'Подкармливайте каждые 2-3 недели в период роста.',
      repottingTips: 'Пересаживайте весной, когда корни заполнят горшок.',
    },
    {
      scientificName: 'Sansevieria trifasciata',
      commonNameRu: 'Сансевиерия (Тёщин язык)',
      commonNameEn: 'Snake Plant',
      description: 'Неприхотливое растение с длинными полосатыми листьями',
      wateringFrequencyDays: 14,
      wateringWinterMultiplier: 0.5,
      wateringSummerMultiplier: 1.0,
      lightLevel: 'LOW',
      humidityLevel: 'LOW',
      temperatureMin: 15,
      temperatureMax: 28,
      lightingTips: 'Выносит любое освещение — от тени до яркого света.',
      wateringTips: 'Поливайте редко. Лучше недолить, чем перелить!',
      humidityTips: 'Не требует опрыскивания. Переносит сухой воздух.',
      feedingTips: 'Подкармливайте раз в месяц в период роста.',
      repottingTips: 'Пересаживайте раз в 2-3 года или когда горшок становится тесным.',
    },
    {
      scientificName: 'Spathiphyllum',
      commonNameRu: 'Спатифиллум (Женское счастье)',
      commonNameEn: 'Peace Lily',
      description: 'Элегантное растение с белыми цветками-покрывалами',
      wateringFrequencyDays: 5,
      wateringWinterMultiplier: 0.7,
      wateringSummerMultiplier: 1.3,
      lightLevel: 'LOW',
      humidityLevel: 'HIGH',
      temperatureMin: 18,
      temperatureMax: 25,
      lightingTips: 'Полутень или рассеянный свет. Избегайте прямого солнца.',
      wateringTips: 'Держите почву слегка влажной. Растение опустит листья при жажде.',
      humidityTips: 'Любит высокую влажность. Часто опрыскивайте.',
      feedingTips: 'Подкармливайте раз в 2 недели весной и летом.',
      repottingTips: 'Пересаживайте каждые 1-2 года весной.',
    },
    {
      scientificName: 'Chlorophytum comosum',
      commonNameRu: 'Хлорофитум',
      commonNameEn: 'Spider Plant',
      description: 'Неприхотливое растение, очищающее воздух',
      wateringFrequencyDays: 7,
      wateringWinterMultiplier: 0.6,
      wateringSummerMultiplier: 1.2,
      lightLevel: 'MEDIUM',
      humidityLevel: 'MEDIUM',
      temperatureMin: 15,
      temperatureMax: 25,
      lightingTips: 'Яркий рассеянный свет, но выносит и полутень.',
      wateringTips: 'Поливайте умеренно, давая почве подсохнуть.',
      humidityTips: 'Периодически опрыскивайте для предотвращения подсыхания кончиков.',
      feedingTips: 'Подкармливайте раз в 2-3 недели весной и летом.',
      repottingTips: 'Пересаживайте ежегодно весной.',
    },
    {
      scientificName: 'Epipremnum aureum',
      commonNameRu: 'Потос (Эпипремнум)',
      commonNameEn: 'Pothos',
      description: 'Вьющееся растение с сердцевидными листьями',
      wateringFrequencyDays: 7,
      wateringWinterMultiplier: 0.6,
      wateringSummerMultiplier: 1.2,
      lightLevel: 'LOW',
      humidityLevel: 'MEDIUM',
      temperatureMin: 15,
      temperatureMax: 27,
      lightingTips: 'От полутени до яркого рассеянного света.',
      wateringTips: 'Поливайте, когда верхний слой почвы подсохнет.',
      humidityTips: 'Среднее увлажнение. Периодическое опрыскивание приветствуется.',
      feedingTips: 'Подкармливайте раз в месяц в период роста.',
      repottingTips: 'Пересаживайте раз в 1-2 года.',
    },
    {
      scientificName: 'Dracaena marginata',
      commonNameRu: 'Драцена окаймлённая',
      commonNameEn: 'Dragon Tree',
      description: 'Изящное растение с тонкими полосатыми листьями',
      wateringFrequencyDays: 10,
      wateringWinterMultiplier: 0.5,
      wateringSummerMultiplier: 1.1,
      lightLevel: 'MEDIUM',
      humidityLevel: 'MEDIUM',
      temperatureMin: 18,
      temperatureMax: 26,
      lightingTips: 'Яркий рассеянный свет. Избегайте прямого солнца.',
      wateringTips: 'Поливайте умеренно, давая почве хорошо просохнуть.',
      humidityTips: 'Опрыскивайте листья для предотвращения подсыхания.',
      feedingTips: 'Подкармливайте раз в месяц весной и летом.',
      repottingTips: 'Пересаживайте раз в 2-3 года.',
    },
    {
      scientificName: 'Zamioculcas zamiifolia',
      commonNameRu: 'Замиокулькас (Долларовое дерево)',
      commonNameEn: 'ZZ Plant',
      description: 'Очень неприхотливое растение с глянцевыми листьями',
      wateringFrequencyDays: 14,
      wateringWinterMultiplier: 0.5,
      wateringSummerMultiplier: 1.0,
      lightLevel: 'LOW',
      humidityLevel: 'LOW',
      temperatureMin: 15,
      temperatureMax: 28,
      lightingTips: 'Выносит любое освещение, включая тень.',
      wateringTips: 'Поливайте редко! Лучше недолить. Клубни накапливают воду.',
      humidityTips: 'Не требует опрыскивания.',
      feedingTips: 'Подкармливайте раз в месяц весной и летом.',
      repottingTips: 'Пересаживайте раз в 2-3 года.',
    },
    {
      scientificName: 'Aloe vera',
      commonNameRu: 'Алоэ вера',
      commonNameEn: 'Aloe Vera',
      description: 'Суккулент с лечебными свойствами',
      wateringFrequencyDays: 14,
      wateringWinterMultiplier: 0.5,
      wateringSummerMultiplier: 1.0,
      lightLevel: 'HIGH',
      humidityLevel: 'LOW',
      temperatureMin: 13,
      temperatureMax: 27,
      lightingTips: 'Яркий свет, может выносить прямое солнце.',
      wateringTips: 'Поливайте редко, давая почве полностью просохнуть.',
      humidityTips: 'Не требует опрыскивания. Предпочитает сухой воздух.',
      feedingTips: 'Подкармливайте раз в месяц летом.',
      repottingTips: 'Пересаживайте раз в 2-3 года.',
    },
    {
      scientificName: 'Calathea',
      commonNameRu: 'Калатея',
      commonNameEn: 'Calathea',
      description: 'Декоративнолистное растение с узорчатыми листьями',
      wateringFrequencyDays: 5,
      wateringWinterMultiplier: 0.7,
      wateringSummerMultiplier: 1.3,
      lightLevel: 'LOW',
      humidityLevel: 'HIGH',
      temperatureMin: 18,
      temperatureMax: 24,
      lightingTips: 'Полутень. Избегайте прямого солнца — листья выцветают.',
      wateringTips: 'Держите почву слегка влажной. Используйте фильтрованную воду.',
      humidityTips: 'Требует высокой влажности! Опрыскивайте ежедневно или используйте увлажнитель.',
      feedingTips: 'Подкармливайте раз в 2 недели весной и летом.',
      repottingTips: 'Пересаживайте ежегодно весной.',
    },
  ];

  for (const sp of species) {
    await prisma.plantSpecies.upsert({
      where: { scientificName: sp.scientificName },
      update: sp as any,
      create: sp as any,
    });
  }

  console.log(`Seeded ${species.length} plant species`);
}
